name: seagrass-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xarray
  - rasterio
  - rioxarray
  - geopandas
  - matplotlib
  - jupyterlab
  - shapely
  - netcdf4
  - pip
  - pip:
    - sentinelhub

