name: publish-book

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          auto-activate-base: true
          activate-environment: seagrass-env
      
      - name: Build the book
        shell: bash -l {0}
        run: |
          jupyter-book build .

 
